name = "cederberg"
license = "MIT"
licenselink = "https://github.com/oscarcederberg/cederberg-theme/blob/master/LICENSE"
description = "cederberg.xyz theme"
homepage = "https://github.com/oscarcederberg/cederberg-theme/"
tags = []
features = ["tailwindcss"]
min_version = "0.1.0"

[author]
  name = "Oscar Cederberg"
  homepage = "https://cederberg.xyz/"
